### ISSUE TITLE
Conversions tracking issue

### ISSUE THREAD

**Issue by jcbhmr** [jcbhmr/webidl#1]
- [x] any
- [ ] undefined
- [ ] boolean
- [ ] byte
- [ ] octet
- [ ] short
- [ ] unsigned short
- [ ] long
- [ ] unsigned long
- [ ] long long
- [ ] unsigned long long
- [ ] float
- [ ] unrestricted float
- [ ] double
- [ ] unrestricted double
- [ ] bigint
- [ ] DOMString
- [ ] ByteString
- [ ] USVString
- [ ] object
- [ ] symbol
- [ ] Interface types
- [ ] Callback interface types
- [ ] Dictionary types
- [ ] Enumeration types
- [ ] Callback function types
- [ ] Nullable types
- [ ] Sequences
- [ ] Records
- [ ] Promise types
- [ ] Union types
- [ ] Buffer source types
- [ ] Frozen arrays
- [ ] Observable arrays
