### ISSUE TITLE
[Milestone] v2

### ISSUE THREAD

**Issue by jcbhmr** [jcbhmr/webidl#3]
- [ ] Add `partial_interface()` decorator
- [ ] Add `namespace()` decorator
- [ ] Add `partial_namespace()` decorator
- [ ] Add `dictionary()` decorator
- [ ] Add `partial_dictionary()` decorator
- [ ] Add `enum()` decorator
- [ ] Add `callback()` decorator
- [ ] Add `callback_interface()` decorator
- [ ] Add `typedef()` decorator
- [ ] Add `const_()` decorator
- [ ] Add `interface_mixin()` decorator
- [ ] Add `partial_interface_mixin()` decorator
- [ ] Add some way to apply mixins to interfaces
- [ ] Add some way to apply partial interfaces to interfaces
- [ ] Add some way to expose interfaces globally
- [ ] Add `stringifier()` decorator
- [ ] Add `getter()` decorator
- [ ] Add `setter()` decorator
- [ ] Add `deleter()` decorator
- [ ] Add an `overload()` router
- [ ] Add `iterable()` decorator
- [ ] Add `async_iterable()` decorator
- [ ] Add `maplike()` decorator
- [ ] Add `readonly_maplike()` decorator
- [ ] Add `setlike()` decorator
- [ ] Add `readonly_setlike()` decorator

**Comment by jcbhmr** [comment]
Should ES decorators be overloads or separate functions?
Should decorators be PascalCase or camelCase?
