### ISSUE TITLE
[Milestone] v1

### ISSUE THREAD

**Issue by jcbhmr** [jcbhmr/webidl#4]
- [x] Create npm package
- [x] #6
- [x] Add some way to coerce arguments
- [x] Add some way to coerce return types
- [ ] Add `attribute()` decorator
- [ ] Add `readonly()` decorator
- [ ] Add examples of vanilla JS usage
- [ ] ~~Add examples of TS ES-decorators usage~~
- [x] Add test Dog (interface) + ~~Pet (mixin) + ServiceDog (extends) + Dog (partial)~~
- [ ] ~~Add ES decorators for these things!~~
- [x] #5
